[project]
name = "NeMo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightning>2.2.1,<=2.4.0",
    "hydra-core>=1.3.2",
    "nemo-toolkit>=2.1.0",
    "numpy>=2.2.6",
]
